global.tips = ["<STARTING TIPS 1-5>", 
				"Hi there! My name is Hunk!\n\n                        (press \"E\", \"Space\", \"Enter\", or left click to proceed)",
				"As you know, the local gym's been getting a little, well...\n...negative",
				"That's why I'm here. I am going to help you get all of these toxic vices out of this gym,\nand out of this community.",
				"To get past these vices, use the syringe gun in your hand to convert the slimey things\nfrom the bad vices they are into positive reinforcement!\n                        (use mouse to aim and left click to fire curing syringe)",
				"There will be a few weak slimes up ahead. Go over and convert them to good vibes!\n\n                        (use WASD/arrow keys to move, and Space to jump)",
				"<WALL DESTRUCTION 7>",
				"Good job getting through those slimes! Your syringe gun is able to break through\ncertain walls just like bad vices. Try breaking through this wall!",
				"<BLOCKING 9-10>",
				"Amazing! You're a natural at this! Try to make your way through the gym to free\nother athletes of their bad vices!",
				"If the slimes begin to overwhelm you, I will be here to help defend you! The more\nslimes you convert and collect, the more I can defend you!\n   (right click to block incoming attacks. the strength of your shield is in the top left)",
				"<DROPPING 12>",
				"These thin platforms allow you to both stand on them, but also to drop through\nthem. Try it out!\n                        (press Ctrl to drop through platforms)",
				"<MINIBOSS PREP 14-18>",
				"Good job making it to this point. Past this wall is a much stronger enemy who has\ncaptured a gym-goer and is sapping their vibes.",
				"If he gets too close, he will launch you back. You will not be able to smoosh him\nlike the others.",
				"Make sure to use me to cushion his attacks and keep your distance.",
				"When he is beaten, the mechanism should fail, allowing you to free the poor soul.",
				"Good luck, and stay natty!",
				"<FINAL WORDS 20-22>",
				"Great job clearing out the gym, but there is much more work to be done.",
				"Even more vices are out in the streets, abducting even more people. We need to\nfree them and find the root cause of all these slimes.",
				"Let's go spread the natty life."
				];